# Generated by Django 3.2.25 on 2024-06-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseme_app', '0005_alter_property_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='account_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='class_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
