# Generated by Django 3.2.25 on 2024-06-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseme_app', '0006_auto_20240605_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='manager_phone',
            field=models.CharField(default='000-000-0000', max_length=50),
        ),
    ]
