# Generated by Django 5.0.6 on 2024-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseme_app', '0007_auto_20240605_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='desired_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='lease_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('renter', 'Renter')], max_length=10),
        ),
    ]
