# Generated by Django 5.0.6 on 2024-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseme_app', '0008_applicant_desired_rent_applicant_lease_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
