# Generated by Django 5.0.6 on 2024-06-19 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseme_app', '0012_propertyimage_delete_listing_property_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
